from __future__ import annotations

import json
import os
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from typing import Protocol


class ProviderError(RuntimeError):
    """Raised when a provider call cannot complete successfully."""


@dataclass(slots=True)
class ProviderResponse:
    provider: str
    model: str
    output_text: str
    metadata: dict[str, str] = field(default_factory=dict)
    provenance: list[str] = field(default_factory=list)


class Provider(Protocol):
    name: str

    def generate(self, *, model: str, prompt: str, system_prompt: str = "") -> ProviderResponse:
        ...


class MockProvider:
    name = "mock"

    def generate(self, *, model: str, prompt: str, system_prompt: str = "") -> ProviderResponse:
        evidence = (
            "Prompt requested source-aware output."
            if "source" in prompt.lower()
            else "Prompt did not explicitly request sources."
        )
        output = (
            f"Mock response for {model}: {prompt}\n"
            "Maybe verify this answer against documentation before using it in production."
        )
        return ProviderResponse(
            provider=self.name,
            model=model,
            output_text=output,
            metadata={
                "transport": "in-process mock",
                "system_prompt_present": "yes" if system_prompt else "no",
            },
            provenance=[evidence, "Generated by the built-in mock provider for local demos."],
        )


class OpenAIProvider:
    name = "openai"
    endpoint = "https://api.openai.com/v1/responses"

    def generate(self, *, model: str, prompt: str, system_prompt: str = "") -> ProviderResponse:
        api_key = os.environ.get("OPENAI_API_KEY")
        if not api_key:
            raise ProviderError("OPENAI_API_KEY is not set.")

        payload = {"model": model, "input": prompt}
        if system_prompt:
            payload["instructions"] = system_prompt

        request = urllib.request.Request(
            self.endpoint,
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )

        try:
            with urllib.request.urlopen(request, timeout=60) as response:
                body = json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise ProviderError(f"OpenAI request failed with HTTP {exc.code}: {detail}") from exc
        except urllib.error.URLError as exc:
            raise ProviderError(f"OpenAI request failed: {exc.reason}") from exc

        return ProviderResponse(
            provider=self.name,
            model=model,
            output_text=_extract_openai_text(body),
            metadata={"response_id": str(body.get("id", "")), "transport": "https"},
            provenance=["Response generated via OpenAI Responses API."],
        )


class AnthropicProvider:
    name = "anthropic"
    endpoint = "https://api.anthropic.com/v1/messages"

    def generate(self, *, model: str, prompt: str, system_prompt: str = "") -> ProviderResponse:
        api_key = os.environ.get("ANTHROPIC_API_KEY")
        if not api_key:
            raise ProviderError("ANTHROPIC_API_KEY is not set.")

        payload = {
            "model": model,
            "max_tokens": 1024,
            "messages": [{"role": "user", "content": prompt}],
        }
        if system_prompt:
            payload["system"] = system_prompt

        request = urllib.request.Request(
            self.endpoint,
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "Content-Type": "application/json",
            },
            method="POST",
        )

        try:
            with urllib.request.urlopen(request, timeout=60) as response:
                body = json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise ProviderError(f"Anthropic request failed with HTTP {exc.code}: {detail}") from exc
        except urllib.error.URLError as exc:
            raise ProviderError(f"Anthropic request failed: {exc.reason}") from exc

        return ProviderResponse(
            provider=self.name,
            model=model,
            output_text=_extract_anthropic_text(body),
            metadata={"response_id": str(body.get("id", "")), "transport": "https"},
            provenance=["Response generated via Anthropic Messages API."],
        )


def get_provider(name: str) -> Provider:
    normalized = name.strip().lower()
    if normalized == "mock":
        return MockProvider()
    if normalized == "openai":
        return OpenAIProvider()
    if normalized == "anthropic":
        return AnthropicProvider()
    raise ProviderError(f"Unknown provider '{name}'. Supported providers: mock, openai, anthropic.")


def _extract_openai_text(payload: dict) -> str:
    for item in payload.get("output", []):
        if item.get("type") != "message":
            continue
        for content in item.get("content", []):
            if content.get("type") == "output_text":
                return str(content.get("text", ""))
    if "output_text" in payload:
        return str(payload["output_text"])
    raise ProviderError("OpenAI response did not include output text.")


def _extract_anthropic_text(payload: dict) -> str:
    for block in payload.get("content", []):
        if block.get("type") == "text":
            return str(block.get("text", ""))
    raise ProviderError("Anthropic response did not include text content.")
